apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: istio-system
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: grafana.alboroto.live
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: grafana
          servicePort: 3000
  - host: tracing.alboroto.live
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: zipkin
          servicePort: 9411
  - host: prometheus.alboroto.live
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: prometheus
          servicePort: 9090
  - host: kiali.alboroto.live
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: kiali
          servicePort: 20001
  # - host: auth.alboroto.live
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         serviceName: authelia-service
  #         servicePort: 80

