apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/alvarogg777/docker-selenium/patch-4.0.0-beta-4-20210608/chart/manifests/selenium-grid.yaml
- prometheus.yaml
- grafana.yaml
- jaeger.yaml
- kiali.yaml
- ingress.yaml
#patchesStrategicMerge:
#- patch-grid.yaml
patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets/-
      value:
        name: regcred
namespace: selenium-system
