apiVersion: release-notes/v2
kind: feature
area: traffic-management
releaseNotes:
- |
  **Added** topology label "topology.istio.io/network" to IstioEndpoint if it does not exist in pod/workload label.
