apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: istio-sytem
spec:
  encryptedData:
    .dockerconfigjson: AgASrXRh5qrt2w/5pV8o7BlufNb8u+MyofFgn1MO0zfh5tJwHDobhnmNG7KMojsjES+N/SEWHqXo8aeC+X1jqbEiKFGNGe/QQrz1LOo1Tw0hUBLW27GeeFb9wv1kMg4LcjxaB61x2q/wDrfZOXxsGwMSOzGhJ+XJdM6i7TZJ3+AkknVCpaUiTNDGJ4njWeqxl9YtGqNC8o9X2DxBTzFmIx89NLGTY9bpfFWSjaYIa7QLFdeFAiAmUMEP9qXs5TC0/hIHsW2HYPsSbr2gRpe8xAXszqv5WWBPnH9wIgjqu00YKI6lXO1WQ+vYGh6BcBy27u0PAZ9j+xtZGRTIxFHvhHj4F5TNYx3MOYj3BTWmPjrVAKO/Xqqjkx7t7yBor2x0k56fw7yfwvrTXLb/oeFZSsMWc1d5FjfDQSu1l392n0jvqFAKWA+uN9dZGj9WXMWzDBXzizZa4QKw0a3KAkhTM8mE9jfKd2pnBqJQcrW49eWkJgwA3mB0Qo7u3Oa4GcZDPs7Gyp0KeEnmblDD523IyqLa4QNyq7irdqtketxMAlvgtzhL9Smo3GBtzjcEJhRp+GQEJ54NiVSXnkHBCS9EJ2VeSl1vpUYEDW4EFT7De4a0Ikrc96vR6DF7+wnGsaNkut5R1ahkjdTXxnOHxG2AZLi1nZFFDVRYiP3r2nD7JCwizF/+Hay9gFyJ4lN36yPqcK+QtJi8k1EuC8YRXJlLSHuJmMok7k52rKr7gunX5NiSe78YcirlC8S1rANKrNzcsHLlPTcHW6b6nCZ4xEglLZ4kTaqQrPsB0a21XTidMJTwLlbrLQJUUvOqNwuZSSXAurQvoY3IMlWByWv7ohdQoQ1CjAoi/CXlQl11zott1zvWyTzA5Rc6T3BDbN6A8+7iT7PET3j/j6u50hjLfN6zwVN3mHWvlXRn
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: istio-sytem
    type: kubernetes.io/dockerconfigjson

