apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: istio-system
spec:
  encryptedData:
    .dockerconfigjson: AgAQMweA88zxvvrtBoYI4ariMmwpr384ed+WXz2I7z+J4x9oka5X67tG+hoXdycWZ9HLXj2B+S1FJeF5jyfJ2493TdK9ec8pfBBVwjhNOUu+0Hsx3MxIeXJzSnZRpAj1T8v/fQPfopQ3KjNGdAuigQbxmGIAu/W2Raa4beMjQahNpAtkCzsMLR7IPq6ecEpjClLvE8ZKhStB1gzKy3JtgX3LcxJdYaTL798gkkuidHve+EXb5T3mD9lYDht/NCYfGHqJwSwcxhykCGffIxzWMB41B2v2ry/9OX2G1pCETplP1FMY1PzYjtd22SQXugT6oBW8wY3zukbhmwTWFJK+CA++nb4xv3er3ME1fTsATAWTPh8NvW/l4a/m+IfG0Gc2Ss+qvXuqHtuDr56B3c0sJ1XInxBQ5GflO1DPVEObGJ1r0lnCfcIVLxJmFmSoMk0vZHGdUg7QsEKOK0eLpxxwNmTyRJeUp9xMjxugRFYVouVlxS56figHX4qXDy+ZIJFiUGqBbOMK9Y2n4OS0323a4x0Y/mpEz+iNR4Tm6OuR6kgLjZrC21pvliTVJJJMRp1jmmZLCH8eK7nJQ1DG+5GGtgrHrXGgUhKUXwiYiIb+UNJFOXG4k3zzIczoqop8IUU0e3ZHv/QoBSwtTCTeVi4ruz8gqowHQp5zYxtwgdxEcCjeECTXvOQMsXF8R7lG8Ls7RKM109ocxrvKiZ7lioMbZZVau0iCVu0WPBfG1L5s91WTu8l5E8bvHOqPjIY+0XAlDODeTZGHlbvU/H5+OsPRoKQY1Ri1FkLLPOdNg72NcQBO8vkXtC8ub7JqQZ+6GyPOHrH/QKCDcG43ZMGYOkRvisZlZPBWS+9/yLC/C2s3QPByBIPc0I7sZWBRRvtmSgrGbMTzG+3f6o4CIKfB0PqLdONINO+M8j2g
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: istio-system
    type: kubernetes.io/dockerconfigjson

