apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: istio-system
spec:
  encryptedData:
    .dockerconfigjson: AgDxoJlGsVD47/6dtJ+d8oJdPOH0HJ/brIGVSMtdYRTzoG2Z3Yl4AAiK7bfqtDwNLE5utLIvJTHj9+bhKJpZbgjxdygmUW0pCO/GHaNccjaPgFEImV0tNu5aZfFLHdfOyRyzlOO2QDGgob5S+wPszPFMdo/W8/ZcaSRTadppw6W1MZSpijGpBNirfYTOvyXhBEZCGzMT98go5purPjLKkysbnQa4fd9UKHQ4OoeyyOcKGnKnY8NTiJ9timFKKmlxDSR84FQQVXF3yn1AI9tptF+1GzYOJilxiilBh0XzyXj4sz82Iyn32AohYiEmbn/XPtrjdBdU0BXw7R6iJpvi79A/6yX2ctR/MHjl3KNLdvE3Ce9JVa2EIRdeGbbHa9KMNsZ5ukRFIZpeVRSfgy9k442nWEFiuUnYTK0E1fIgESE18yT7bUgGFEc15GwidhkYSTidU29NeRcYIvJy4s+CS2NA0PFaXmQ+1KaulnZ+sH8XOj4JGlutE76TKHAWbV+19neyn2C4cEh8r6J0Y8u+9Q6svVHGOGdn0puJ4KrRYSiR0tCA3pCos0bd1OKTu+oC1ZFr8ZATFlj9ZPpUgZF2IPI6JI7SBpklddNzd1Rh0PXcdvhjbnsQ+0C3FkfEVb554CSnWgtcILHPCNFW1eCLWGGCOVHq05qsJr+Lk0R5J4MTljvfWTohu9y+fQgbdrZIFI7e4F120kbmKzzJdVlwYckgwgK5RUO020RD/M+pEsECYbk2A+nlvbo5AMP/cfF+Iuhia2yPgZGkueajdEKeq6/PrvTcU22BgEeyTMMh3ryrVWytD5bUYSBt6/hl5Pp3/AZMnxmdPB+owYU05KV5xubLIU1j8HFEPgs0g9xUKwm6iL9K1dJ+C5I1eTAI562C7LmpccalixJUjdGVEGf7kTyqHKDfgLOA
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: istio-system
    type: kubernetes.io/dockerconfigjson

