apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: istio-system
spec:
  encryptedData:
    .dockerconfigjson: AgBvPpCcOWtuwmkvF6fcPS2LBhpGRT+F5QNSHy4GKTcFVY81i8r4u9AV8GMZiuri/NKL2ix/B/x1EuBd3V2cfQ2RRe6rr76mUVSsdYMSwVJuff9+jJb/OgbFjS8jxrXaK6MwfkJxjqckp9ny9zbFAX5trhy+dK/9eOPsISuBsD2LEGQM/eeSWhwMUwVVuYCzZXfKyL3FUnMHz4iHX+JHhaxHi4PvA+eo2z/tEuYKdFLDVQxrRyEek9Bg3CA9wjE9/rKPS4HJt7ony/dTeHVDS+WnEY4DmjOcUoUzqpPqH56uZZM4Y3/3ewweVhezlXVQArYYza8SHEsEGbqb/p8daYfpJAPopcpV4BsQf5eoFbd29o+cfaAG3yV67TGoZ33p2wG1uN29ZL0HCK+BdP9o45v/T0bt5vN0zpsKCEekTE+O+NQ8CzU/XhfC1JuCnJ6ARuNN0DWp1gzr29D09xUaYNVweIc++h1bloTz1Ff5I31ce6Poy04RHrlJyCDLZCMwua7iEDezv7JsUApCMzZ8dDanHg2CDbHz/m2seGQ/LXOeq+e9MU8Olz0f9uaa3VflSTdY51KzTSwWkUXuglexY28tVeKMq9ME2/malQ8MT2DeSvoK5f366f/kN59tM8CGCHYaL7/RhSiF890L3q0BA2owgls35xyFrqZWq70vYEMpkaCesztjX1piyflgIYrJuQrso6v2smsRGD3X/tRErsxcAoYXScMGWuj2/PukZjt0LsCNjJrp/6NlsMs+wCuOCHN0Stq+kKx+Q57r99aOcWSEH2RU57UhGlu2JbGV+kktUnT5vyV3LYN34Y0ipbn7dZgzgl5C7RQSjOL5yhMkMTtXr9Klye6WeHkbmc+r95YahKEkctoEzsW+DqNo2kPWKvsXMTPDrmbIxWkO2X59Xxxnbt9qncIK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: istio-system
    type: kubernetes.io/dockerconfigjson

