apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: istio-system
spec:
  encryptedData:
    .dockerconfigjson: AgA8pZHo7nKsEK7+CpL+W+VZRBQDnGPrEv+eE14tYTxMCLDy4aOnMw001aPulaUkpdjhD0cfM1sVVQh1d6NHsTUBWZetWvfkJ5FW45s5u5U62fsnMkAsI6yTMAY48o+hIP89a+abH4EQbCgN52ndzIIzgC4KXIH1iLS5tZ/cdXCma/tOIsFzhsBS2sH71aV8fmv0gWIJJtzmkATXqvBfOw+FcFTNTY/hUQKxy6IL8nUldNE6jqw7UqoMpXTODE9EVqiOktSF/0cCPXSL4xoG96DrV6aB3mxSUsYU3DrLJN5Q0zMSSY+10NcLbzqttVSXHbCC/SvUHfuxrlzsIEFHfEVKr7iwAIcwbmC3UeAyEXxPrd+Vij7ekYMVVhjoeqr+vAiGYao9C1XB2hsSL2/vqL/pQX/vGn3TkdigbxnLew+MvAaqHmztpfToHeKUHu9d7K9+OZZmxqVx4UJ4D/I/xj0Ty3h4KVD1mvOVG30zk1NMvSwVdQjiuqs9RfjYsjpAXodv5V7Vd7U4vRqHMWCL+tRZXAV/MuAe8PGB28XilIwRcSduUpFhs6M6C+PFxUNEqBAXoYA0B1RPQUOhaZhRYhjKmmk65RBfPqPMTVfpd8IOsh6Ac5L9jmX/MpwXyCSyjjMpnp4ivbAEM6NUob7odOqb13vhd0qnv1VsYHYa5OZd81Is2KrSr8HOHwYLvBwR4tVnP6Gt2cjXQZ22RuFnHBKDf6XBLyWBacnw3vZld6GLZcW7nNUJ0n/nC3or91aYLB7QyEusvIEBr2hoE+PcVEwFiPwLGs6HNmPO1GxTiKXc13MkXw7XUalrkAIuPJsLSaod55DLMTwWgwvZcPPGFplah02kT90qOc2XHF77AHs7niiy4FKstoj9KzDlUW02nYC76vcODINV07LI9KlOSiPWqflCHcrt
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: istio-system
    type: kubernetes.io/dockerconfigjson

